[core_switches]
hq-core-sw01 ansible_host=10.10.10.5
hq-core-sw02 ansible_host=10.10.10.6

[edge_routers]
branch-router-01 ansible_host=192.168.100.1
branch-router-02 ansible_host=192.168.100.2

[all:vars]
ansible_connection=network_cli
ansible_network_os=cisco.ios.ios
ansible_user=netadmin
ansible_ssh_pass=Vault_Secure_Password_Placeholder
